# Generated by Django 5.0.7 on 2024-07-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='country',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
