# Generated by Django 5.0.7 on 2024-07-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_statistics_country_alter_statistics_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
