# Generated by Django 5.0.7 on 2024-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_statistics_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
