# Generated by Django 5.0.7 on 2024-07-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='count',
            new_name='querys',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='count',
            new_name='querys',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citys', to='app.country'),
        ),
    ]
