x-app_environment: &app_environment
  environment:
    # Postgres
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_NAME
    # Telebot
    - BOT_TOKEN
    # NGROK url
    - HTTPS_URL

services:
  db:
    restart: unless-stopped
    image: postgres:16.3-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER
  
  backend:
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - 8000:8000
      # aerich upgrade &&
    command: sh -c "python wait-for &&
                    uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    <<: *app_environment
  
  bot:
    restart: unless-stopped
    build:
      context: ./bot
    command: sh -c "python main.py"
    volumes:
      - ./bot:/app
    depends_on:
      - backend
    <<: *app_environment
