# Generated by Django 4.2.10 on 2024-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_avilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_avilable',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
