# Generated by Django 5.1 on 2024-08-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accaunt',
            new_name='Account',
        ),
    ]
