# Generated by Django 5.1 on 2024-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_rename_accaunt_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('dispatch_date', models.DateTimeField()),
                ('receive_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('files', models.CharField(max_length=255)),
            ],
        ),
    ]
