# Generated by Django 5.1 on 2024-09-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mail.account'),
            preserve_default=False,
        ),
    ]
