# Generated by Django 5.1 on 2024-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mail_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_id',
            field=models.CharField(max_length=255),
        ),
    ]
