# Generated by Django 5.0.7 on 2024-08-13 10:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='named_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
