# Generated by Django 5.0.7 on 2024-08-14 07:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
    ]
